// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlTf_4hsY2g9_KA_JTIbi73NclJ6PcGIM',
    appId: '1:949321676986:web:fb6b8844d012de9e7baa83',
    messagingSenderId: '949321676986',
    projectId: 'vinted-d08cf',
    authDomain: 'vinted-d08cf.firebaseapp.com',
    storageBucket: 'vinted-d08cf.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLkpqnsyFyXWQvZYzcqN-c3UlkLIPNCeE',
    appId: '1:949321676986:android:7d612997bec94a7d7baa83',
    messagingSenderId: '949321676986',
    projectId: 'vinted-d08cf',
    storageBucket: 'vinted-d08cf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5N3lICDj2uDAHoPa1sORsrFuAO1kad8s',
    appId: '1:949321676986:ios:25cbc6ca6a5e3a4b7baa83',
    messagingSenderId: '949321676986',
    projectId: 'vinted-d08cf',
    storageBucket: 'vinted-d08cf.appspot.com',
    iosClientId: '949321676986-7mo2lceqndtcmo1qov0oqqqr1gg72rhe.apps.googleusercontent.com',
    iosBundleId: 'com.example.vintedMiage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5N3lICDj2uDAHoPa1sORsrFuAO1kad8s',
    appId: '1:949321676986:ios:25cbc6ca6a5e3a4b7baa83',
    messagingSenderId: '949321676986',
    projectId: 'vinted-d08cf',
    storageBucket: 'vinted-d08cf.appspot.com',
    iosClientId: '949321676986-7mo2lceqndtcmo1qov0oqqqr1gg72rhe.apps.googleusercontent.com',
    iosBundleId: 'com.example.vintedMiage',
  );
}
